micronaut:
    application:
        name: revolut

datasources:
    default:
        url: 'jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
        username: 'sa'
        password: ''
        driverClassName: 'org.h2.Driver'

jpa:
    default:
        packages-to-scan:
        - 'br.com.erick.revolut.repository.entity'
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: true

flyway:
    datasources:
        default:
            locations: classpath:scripts